allowed-tweakers:
    - cpw.mods.fml.common.launcher.fmltweaker
    - cpw.mods.fml.common.launcher.fmlinjectionandsortingtweaker
    - cpw.mods.fml.common.launcher.fmldeobftweaker
    - cpw.mods.fml.common.launcher.terminaltweaker
    - optifine.optifineforgetweaker
    - shadersmodcore.loading.smctweaker
    - org.spongepowered.asm.mixin.mixinenvironment$environmentstatetweaker
    - com.almuradev.almura.launch.almuralaunchtweaker
allowed-mods:
    - almura
    - almurasdk
    - baubles
    - bibliocraft
    - buildcraft|builders
    - buildcraft|core
    - buildcraft|robotics
    - buildcraft|silicon
    - buildcraft|energy
    - buildcraft|factory
    - buildcraft|transport
    - carpentersblocks
    - cofhcore
    - compactsolars
    - customspawner
    - customnpcs
    - guide
    - ic2
    - inventorytweaks
    - ironchest    
    - malisiscore
    - malisisdoors
    - mantle
    - mapwriter
    - minefactoryreloaded
    - minefactoryreloaded|compatbacktools
    - minefactoryreloaded|compatextrabiomes
    - minefactoryreloaded|compattwilightforest
    - minefactoryreloaded|compatchococraft
    - minefactoryreloaded|compatprojred
    - minefactoryreloaded|compatmystcraft
    - minefactoryreloaded|compatic2
    - minefactoryreloaded|compatatum
    - minefactoryreloaded|compattconstruct
    - minefactoryreloaded|compatappliedenergistics
    - minefactoryreloaded|compatbuildcraft
    - minefactoryreloaded|compatthaumcraft
    - minefactoryreloaded|compatrailcraft
    - minefactoryreloaded|compatforestry
    - minefactoryreloaded|compatsufficientbiomes
    - minefactoryreloaded|compatvanilla
    - minefactoryreloaded|compatforgemicroblock
    - minefactoryreloaded|compatthermalexpansion
    - mocreatures
    - railcraft
    - thaumcraft
    - thermaldynamics
    - thermalexpansion
    - thermalfoundation
    - tconstruct
    - waila