name: AlmuraForgeBridge
main: com.almuramc.forgebridge.BridgePlugin
version: 2.0
authors: [AlmuraDev]
commands:
    bridge:
        description: The general command of Bridge.
        aliases: 
        usage: /bridge [command] [arguments]
permissions:
    bridge.info:
        description: Allows users to view chunk inforatmion.
        default: op
    bridge.debug:
        description: Allows users to view chunk debug inforatmion.
        default: op
    bridge.clearitems:
        description: Allows users to clear items on the server.
        default: op        