name: AlmuraForgeBridge
main: com.almuramc.forgebridge.BridgePlugin
version: 2.0
authors: [AlmuraDev]
commands:
    bridge:
        description: The general command of Bridge.
        aliases: 
        usage: /bridge [command] [arguments]
permissions:
    bridge.title:
        description: sends title packets to players
        default: op
    bridge.info:
        description: Allows users to view chunk information.
        default: op
    bridge.debug:
        description: Allows users to view chunk debug information.
        default: op
    bridge.clearitems:
        description: Allows users to clear items on the server.
        default: op        
    bridge.config:
        description: Allows admins to reload configuration.
        default: op      